# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "pins-r")
v <- vetiver_pin_read(b, "dcp_ibese_truck_arrival", version = "20230110T094207Z-69661")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
